# Generated by Django 5.0.6 on 2024-05-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('type', models.CharField(choices=[('VAL', 'Value'), ('PRCNT', 'Percentage')], default='VAL', max_length=5)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
