# Generated by Django 5.0.6 on 2024-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, null=True, to='products.category'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
    ]
