# Generated by Django 5.0.6 on 2024-06-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productpricehistory_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricehistory',
            name='color',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
    ]
