import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header/Header";
import Navigation from "@/components/layout/header/Navigation";
import Footer from "@/components/layout/footer/Footer";
import { usePathname } from "next/navigation";
import classNames from "@/utils/classNames";
import WholeHeader from "@/components/layout/header/WholeHeader";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <WholeHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
